### ISSUE TITLE
SubscribedCollection find is returning unexpected results

### ISSUE THREAD

**Issue by rsage28** [ShivamArora/meteorify#10]
Here is my server side publication (slightly modified for anonymity purposes):
```javascript
Meteor.publish('samplePublication', function({ query, ID1, limit, search, from, to, ID2, unread }) {
  if (!query)
    query = { $and: [{ ID1: `${ID1}` }] };
  if (from && to) {
    query = {
      $and: [query, { mostRecent: { $gte: from, $lte: to } }]
    };
  }

  if (unread) {
    query.$and.push({ read: { $ne: Meteor.userId() } });
  }

  if (ID2) {
    query.$and.push({ ID2: ID2 });
  }

  if (search && search !== '') {
    const tokens = search.split(' ');
    tokens.forEach(token => {
      const regex = new RegExp(token, 'g');
      query.$and.push({
        $or: [
          { name: { $regex: regex, $options: 'i' } },
          { gender: { $regex: regex, $options: 'i' } }
        ]
      });
    });
  }

  return LabResults.find(query, { sort: { mostRecent: -1 }, limit });
});
```

This is my Flutter code (also modified):
```dart
Future<List<ResultListModel>> items(
      int limit, String search, Function updateListener) async {
    UserModel user = await currentUser();
    await Meteor.subscribe('samplePublication', args: [
      {'ID1': user.profile.ID1, 'limit': limit, 'search': search}
    ]);
    SubscribedCollection collection = await Meteor.collection('collection');
    Map<String, Map<String, dynamic>> results = collection.findAll();
    List<ResultListModel> itemsList = new List<ResultListModel>();
    results.forEach((key, value) {
      ItemListModel item = ItemListModel.fromJson(value);
      item.id = key;
      itemList.add(item);
    });
    collection.addUpdateListener(updateListener);
    return itemList;
  }
```

The results are correctly filtered by `ID1` and `limit`, but when I start trying to search with `search`, two things happen. First, the limit becomes completely ignored, increasing the number of results. And second, the search doesn't actually do any limiting. This is only on the Flutter side, everything works correctly on the server. So I think there's a strange interaction with the subscription here. Any help would be much appreciated.

**Comment by ShivamArora** [comment]
Hi @rsage28, thanks for reporting this out.

I'll look out if it's a bug.

Meanwhile, can you make sure that when using `ID1`, `limit` and `search` the server is sending all the filtered and limited search results?

**Comment by rsage28** [comment]
@ShivamArora When I print out the query results on the server before returning in the publication, it is working correctly. There is also a web client using that publication that works correctly, so I know it's not the publication that's misbehaving. However, I have patched the problem by performing a local query using the in-memory objects in Flutter, which seems to work quite quickly.
