### ISSUE TITLE
login with username

### ISSUE THREAD

**Issue by YouSour** [ShivamArora/meteorify#11]
hi  @ShivamArora , what should i do if  i want to login with username 🤔  , ReadMe document i don't see any example about it, pls, show me the right way, thank you in advance

**Comment by ShivamArora** [comment]
Hi @YouSour ,

Thanks for reporting this out.

The package doesn't currently support login with username.

However, I'll try to add support for the same during this weekend and if I get enough time release an update for the same.

**Comment by YouSour** [comment]
@ShivamArora thank you , i'm waiting for it , bro

**Comment by ShivamArora** [comment]
@YouSour As agreed, I've pushed an update to the package today. Please give it a try and let me know if I can close this issue now.

**Comment by YouSour** [comment]
ok , bro , i will try it @ShivamArora

**Comment by YouSour** [comment]
it works , bro @ShivamArora

**Comment by ShivamArora** [comment]
@YouSour Thanks for the confirmation. Closing the issue now
