### ISSUE TITLE
Subscriptions (The method 'add' was called on null)

### ISSUE THREAD

**Issue by yuniit** [ShivamArora/meteorify#12]
Hello @ShivamArora  I have a problem with Subscriptions it give error like this:

![Screenshot from 2020-08-10 09-27-32](https://user-images.githubusercontent.com/30621352/89748410-3e90c200-daed-11ea-92a2-e53c8b8071f9.png)

Pls, Correct me if I do wrong.

**Comment by ShivamArora** [comment]
@yuniit You should subscribe to a collection only after the connection has been established.

Here, in your case Dart might be calling `Meteor.subscribe` when the future for `Meteor.connect` hasn't been completed yet.

You need to ensure that a call to `Meteor.subscribe()` is made only after a connection has been established.

To do that, you should either subscribe within the `then` clause:

**Solution 1:**
```dart
Meteor.connect('ws://$ip/websocket').then((status) {
   print('Status: $stattus);
   var subId = await Meteor.subscribe('app.company');
}).catchError((error) {
   print('Error: $error');
});
```

Or use `async-await` with both of them:

**Solution 2:**
```dart
try{
   ConnectionStatus status = await Meteor.connect('ws://$ip/websocket');
   print('Status: $status');
   // Subscribe
   var subId = await Meteor.subscribe('app.company');
   print('Subscription Id: $subId);
} catch(error){
   print('Error: $error');
}
```

I hope this helps and solves your issue.

**Comment by yuniit** [comment]
It work well @ShivamArora 
Great thank.
