### ISSUE TITLE
How can I use `subscribe` for real time data ?

### ISSUE THREAD

**Issue by Navyroot** [ShivamArora/meteorify#13]
I use `meteorify` in my project , use `Subscribe` for real time data when I change data on my collection in `mongodb`. Please help me , How can I do?

**Comment by ShivamArora** [comment]
Hi @Navyroot ,

Can you checkout the solution provided at this link in a closed issue?
[Issue #3 ](https://github.com/ShivamArora/meteorify/issues/3#issuecomment-525681979)

**Comment by Navyroot** [comment]
Hi @ShivamArora ,I'm new for flutter. Can you explain me how to use for real time data ?

**Comment by ShivamArora** [comment]
Please refer to the [Flutter Official Docs](https://flutter.dev/docs) for learning flutter.
