### ISSUE TITLE
Get `_id` from `subscribe` meteor 

### ISSUE THREAD

**Issue by Navyroot** [ShivamArora/meteorify#15]
Hi bro @ShivamArora , I try to get `_id` from `subscribe` .
My code : 
```js
  void items() async {
    await Future.delayed(Duration(seconds: 1));
    SubscribedCollection itemCol = await Meteor.collection('items_sub');

    var sub = itemCol.findAll();
    sub.forEach((key, value) {
      print("doc ::::: $value");
      data.add(TodoModel(
        id: value["_id"], // null
        name: value['name'],
      ));
    });
  }
```
Result : 
![image](https://user-images.githubusercontent.com/31533986/91013399-d88a5b80-e611-11ea-95bc-aaa25c2b057e.png)

**Comment by ShivamArora** [comment]
This is strange behavior. Have you tried to debug the data being returned from subscription within Meteor?

**Comment by davinderkumar** [comment]
I also got same issue. 
however, the "key" from forEach is the "_id"

**Comment by ShivamArora** [comment]
@davinderkumar Thanks for finding out. I hope this solves @Navyroot 's issue. Let me know if I need to reopen this.
