### ISSUE TITLE
Clearing collection data from other subscriptions

### ISSUE THREAD

**Issue by davinderkumar** [ShivamArora/meteorify#18]
Hi @ShivamArora 
How can I reset / clear a client side collection which was populated from a subscription.
I have multiple subscription returning data from same collection but of different context / user. so I want that previously collected data in collection should not be there.
Thanks

**Comment by davinderkumar** [comment]
I see unsubscribe does that.

**Comment by ShivamArora** [comment]
Great to see you found a solution on your own. @davinderkumar
