### ISSUE TITLE
addUpdateListener for subscription

### ISSUE THREAD

**Issue by ivanesi** [ShivamArora/meteorify#3]
Hello. Why it returns just subscriptionId when subscribing to collection? How to listen for change?
`collection.addUpdateListener(myListener);`

**Comment by ShivamArora** [comment]
@ivanesi You can listen for changes using the following syntax:
```dart
var updateListener = (String collection,String operation,String id,Map<String,dynamic> document){
   print(operation);
   print(document);
}

collection.addUpdateListener(updateListener);
```
