### ISSUE TITLE
 Collection update ,How can I get the result?

### ISSUE THREAD

**Issue by xiaodusx1** [ShivamArora/meteorify#4]
I use meteorify in my project,when mongo collection changed ,I want know it.
Meteor.connectionListener only give me connectionStatus.

**Comment by ShivamArora** [comment]
@xiaodusx1 Please refer to my comment in this closed issue:
https://github.com/ShivamArora/meteorify/issues/3#issuecomment-525681979

**Comment by xiaodusx1** [comment]
@ShivamArora It work,thank u.

**Comment by ShivamArora** [comment]
Thanks for the response. I think it's better to close this now and update the README regarding this, so other people don't create duplicate issues regarding this.
