### ISSUE TITLE
subscribe need more parameter

### ISSUE THREAD

**Issue by xiaodusx1** [ShivamArora/meteorify#6]
new Meteor.subscribe only one,String subscriptionName,sometimes we need more to control the subscribe,like limit.so I suggest you can add a list parameter.example:
static Future<String> subscribe(String subscriptionName,{List options}) async {
  //static Future<String> subscribe(String subscriptionName) async {
    options??=[];
    Completer<String> completer = Completer<String>();
    Call result = await _client.sub(subscriptionName, options);
......

**Comment by ShivamArora** [comment]
Can you please provide the list of options you would like to pass in and what other controls do you want over subscriptions?

**Comment by xiaodusx1** [comment]
for example:
meteor server publish for this,have some Arguments,
 Meteor.publish('something', function(selector,limitNum) {
 return db.find({$and:selector},{sort:{time:-1}, limit:limitNum});
});
so,we need subscribe to give Parameters.

**Comment by xiaodusx1** [comment]
BTW,method  getMeteorDatabase() have the same :
String dbUrl = "mongodb://" + uri.host + ":3001/meteor";
Usually,the port,db is't  ":3001/meteor".
Though,we can use getCustomDatabase.

**Comment by ShivamArora** [comment]
Thanks for reporting this out.

Both of these issues have now been fixed in the latest updated version `1.0.5`.

Please refer to the [changelog here](https://pub.dev/packages/meteorify#-changelog-tab-)
