### ISSUE TITLE
Demo app making authenticated calls?

### ISSUE THREAD

**Issue by brylie** [ShivamArora/meteorify#8]
Is there a demo app that shows how to authenticate a user and make authenticated method calls and subscriptions?

**Comment by ShivamArora** [comment]
@brylie I cannot provide source code of the apps which are using this library.

The **README** includes code snippets regarding how to authenticate the user and make authenticated calls and subscriptions.

If you know any free Meteor backend which is publically available, then please share it with me.

I'll be happy to develop and release an example app in Flutter with its source code.

**Comment by brylie** [comment]
Just a code example would probably suffice. E.g. a few lines showing how to authenticate and then make an authenticated call to a Meteor method.

**Comment by ShivamArora** [comment]
@brylie You can read the README for that.
It has sufficient code snippets relating to:
1. [Establishing the connection](https://github.com/ShivamArora/meteorify/blob/master/README.md#connection-operations)

2. [Authenticating the user](https://github.com/ShivamArora/meteorify/blob/master/README.md#authentication)

3. [Calling Meteor methods](https://github.com/ShivamArora/meteorify/blob/master/README.md#authentication)

**Comment by brylie** [comment]
Ok, so the `Meteor` object will maintain the user session? Does an instance need to be kept in the app state?

I suppose what I am asking for is just a unified example code snippet showing a simplistic Flutter app that authenticates and makes a method call against a hypothetical Meteor app. That would put the pieces together in a meaningful way.

Has this project been used in any demo or open-source apps?

**Comment by ShivamArora** [comment]
> Ok, so the `Meteor` object will maintain the user session? Does an instance need to be kept in the app state?

@brylie Yes. The user session is maintained internally until the app restarts.

**To maintain the user session across app restarts, you need to persist the login token being returned from the login function and store them using shared preferences or sqlite db.**

For a quick summary, use the following to establish connection
```dart
var status = await Meteor.connect("ws://example.meteor.com");
if(status == ConnectionStatus.CONNECTED){
  // proceed to login
} 
else{
  // show connection error
}
```

And then the following to login:
```dart
var loginToken = await Meteor.loginWithPassword(email,password);
```

Now this `loginToken` needs to be persisted to device to maintain session across app restarts using the shared preferences or sqlite database or any other mechanism you like.

On app restart, you can retrive this token which has been persisted to device earlier and then login using the same token without asking the user again for the email and password.

```dart
var newToken = await Meteor.loginWithToken(loginToken);
```

I hope this clears out your doubt regarding maintaining the user session.

**Comment by ShivamArora** [comment]
> Has this project been used in any demo or open-source apps?

@brylie I would like to develop an open-source demo app provided a public Meteor backend exists to make it work. So, it really acts as a demo and not just a code sample.

Apart from that, I'm not aware if someone else has used this package in their open-source project. We cannot track that out.

**Comment by brylie** [comment]
Thanks for the clarification. It is just really difficult to see how to architect an app with just glimpses into the overall picture mentioned in the README and this conversation.

> I would like to develop an open-source demo app provided a public Meteor backend exists 

Have you tested this package with an app running on localhost? That code might be a good start for sharing, so people can see how this works in context.

**Comment by ShivamArora** [comment]
Yes. I'm even using the package at one of the apps we've developed in my company. 

That was the original motivation behind developing this package for flutter.

But since that's not a personal project, I cannot share the code snippets from that app.

I know we really need an example app to demonstrate the working but for that I need to develop a complete Meteor backend as well to demonstrate various use cases of this package.

But for starting out, if you're aware of working with `Future`s in Dart, that's all you need. There's nothing special that you would need to interact with this package in Flutter.

**Comment by ShivamArora** [comment]
@brylie Do you have any more questions? If not, can I close this issue now?

**Comment by brylie** [comment]
No other questions, thanks.

**Comment by brylie** [comment]
Hey. Here is an example of the kind of documentation that might be useful for a new developer just picking up your project:
https://medium.com/@tanutapi/writing-flutter-mobile-application-with-meteor-backend-643d2c1947d0

The article author creates a trivial Meteor app and then shows how to use their Flutter wrapper to interact with the Meteor app.

Having a holistic view of the development process helps people understand how to get started quickly, by including context otherwise left out of programming-API-level documentation.
